name: VictoriaWebSolutions
favicon: null
layout_spectrum: 0.5381802765186876
typography_spectrum: 0.31712109223008156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#343434'
    - '#7e7e7e'
    - '#01ffff'
  brandStrength: 0.6673604208044708
  lightness: 0.7284281887114048
  saturation: 0.679144305177033
  rhythmicContrast: 0.09513132483698428
purpose: []
