name: VictoriaWebSolutions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31712109223008156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#343434'
    - '#7e7e7e'
    - '#01ffff'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
